/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionBar: typeof import('./src/components/ActionBar/index.vue')['default']
    CreateFolder: typeof import('./src/components/uploadDialog/CreateFolder.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FileGrid: typeof import('./src/components/FileGrid/index.vue')['default']
    FileItem: typeof import('./src/components/FileGrid/FileItem.vue')['default']
    PathNavigation: typeof import('./src/components/PathNavigation/index.vue')['default']
    RightMenu: typeof import('./src/components/RightMenu/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tempfile_1761320223154: typeof import('./src/components/RightMenu/tempfile_1761320223154.vue')['default']
    UploadDialog: typeof import('./src/components/uploadDialog/index.vue')['default']
    UploadFile: typeof import('./src/components/uploadDialog/UploadFile.vue')['default']
  }
}
